export default {
  GET_API_CONFIG: "GET_API_CONFIG",
  GET_API_CONFIG_SUCCESS: "GET_API_CONFIG_SUCCESS",
  GET_API_CONFIG_FAILURE: "GET_API_CONFIG_FAILURE",

  GET_API_STATUS: "GET_API_STATUS",
  GET_API_STATUS_SUCCESS: "GET_API_STATUS_SUCCESS",
  GET_API_STATUS_FAILURE: "GET_API_STATUS_FAILURE",

  GET_REPO_LIST: "GET_REPO_LIST",
  GET_REPO_LIST_SUCCESS: "GET_REPO_LIST_SUCCESS",
  GET_REPO_LIST_FAILURE: "GET_REPO_LIST_FAILURE"
};
