export default {
  CLEAR_ACCESS_TOKEN: "CLEAR_ACCESS_TOKEN",
  REHYDRATE_AUTH_TOKEN: "REHYDRATE_AUTH_TOKEN",

  GET_API_CONFIG: "GET_API_CONFIG",
  GET_API_CONFIG_SUCCESS: "GET_API_CONFIG_SUCCESS",
  GET_API_CONFIG_FAILURE: "GET_API_CONFIG_FAILURE",

  GET_API_STATUS: "GET_API_STATUS",
  GET_API_STATUS_SUCCESS: "GET_API_STATUS_SUCCESS",
  GET_API_STATUS_FAILURE: "GET_API_STATUS_FAILURE",

  LOGIN_USER_GITHUB_OAUTH: "LOGIN_USER_GITHUB_OAUTH",
  LOGIN_USER_GITHUB_OAUTH_SUCCESS: "LOGIN_USER_GITHUB_OAUTH_SUCCESS",
  LOGIN_USER_GITHUB_OAUTH_FAILURE: "LOGIN_USER_GITHUB_OAUTH_FAILURE",

  REFRESH_AUTH_TOKEN: "REFRESH_AUTH_TOKEN",
  REFRESH_AUTH_TOKEN_SUCCESS: "REFRESH_AUTH_TOKEN_SUCCESS",
  REFRESH_AUTH_TOKEN_FAILURE: "REFRESH_AUTH_TOKEN_FAILURE",

  GET_MY_PROFILE: "GET_MY_PROFILE",
  GET_MY_PROFILE_SUCCESS: "GET_MY_PROFILE_SUCCESS",
  GET_MY_PROFILE_FAILURE: "GET_MY_PROFILE_FAILURE",

  CREATE_ENVIRONMENT: "CREATE_ENVIRONMENT",
  CREATE_ENVIRONMENT_SUCCESS: "CREATE_ENVIRONMENT_SUCCESS",
  CREATE_ENVIRONMENT_FAILURE: "CREATE_ENVIRONMENT_FAILURE",

  GET_ENVIRONMENTS_LIST: "GET_ENVIRONMENTS_LIST",
  GET_ENVIRONMENTS_LIST_SUCCESS: "GET_ENVIRONMENTS_LIST_SUCCESS",
  GET_ENVIRONMENTS_LIST_FAILURE: "GET_ENVIRONMENTS_LIST_FAILURE",

  GET_REPOSITORIES: "GET_REPOSITORIES",
  GET_REPOSITORIES_SUCCESS: "GET_REPOSITORIES_SUCCESS",
  GET_REPOSITORIES_FAILURE: "GET_REPOSITORIES_FAILURE",

  GET_USER_REPOSITORIES_LIST: "GET_USER_REPOSITORIES_LIST",
  GET_USER_REPOSITORIES_LIST_SUCCESS: "GET_USER_REPOSITORIES_LIST_SUCCESS",
  GET_USER_REPOSITORIES_LIST_FAILURE: "GET_USER_REPOSITORIES_LIST_FAILURE",

  FIND_GYM_REPOS: "FIND_GYM_REPOS",
  FIND_GYM_REPOS_SUCCESS: "FIND_GYM_REPOS_SUCCESS",
  FIND_GYM_REPOS_FAILURE: "FIND_GYM_REPOS_FAILURE"
};
