export default {
  CLEAR_ACCESS_TOKEN: 'CLEAR_ACCESS_TOKEN',
  REHYDRATE_AUTH_TOKEN: 'REHYDRATE_AUTH_TOKEN',

  GET_API_CONFIG: 'GET_API_CONFIG',
  GET_API_CONFIG_SUCCESS: 'GET_API_CONFIG_SUCCESS',
  GET_API_CONFIG_FAILURE: 'GET_API_CONFIG_FAILURE',

  GET_API_STATUS: 'GET_API_STATUS',
  GET_API_STATUS_SUCCESS: 'GET_API_STATUS_SUCCESS',
  GET_API_STATUS_FAILURE: 'GET_API_STATUS_FAILURE',

  LOGIN_USER_GITHUB_OAUTH: 'LOGIN_USER_GITHUB_OAUTH',
  LOGIN_USER_GITHUB_OAUTH_SUCCESS: 'LOGIN_USER_GITHUB_OAUTH_SUCCESS',
  LOGIN_USER_GITHUB_OAUTH_FAILURE: 'LOGIN_USER_GITHUB_OAUTH_FAILURE',

  LOGOUT_USER: 'LOGOUT_USER',
  LOGOUT_USER_SUCCESS: 'LOGOUT_USER_SUCCESS',
  LOGOUT_USER_FAILURE: 'LOGOUT_USER_FAILURE',

  REFRESH_AUTH_TOKEN: 'REFRESH_AUTH_TOKEN',
  REFRESH_AUTH_TOKEN_SUCCESS: 'REFRESH_AUTH_TOKEN_SUCCESS',
  REFRESH_AUTH_TOKEN_FAILURE: 'REFRESH_AUTH_TOKEN_FAILURE',

  GET_USER_PROFILE: 'GET_USER_PROFILE',
  GET_USER_PROFILE_SUCCESS: 'GET_USER_PROFILE_SUCCESS',
  GET_USER_PROFILE_FAILURE: 'GET_USER_PROFILE_FAILURE',

  UPDATE_USER_PROFILE: 'UPDATE_USER_PROFILE',
  UPDATE_USER_PROFILE_SUCCESS: 'UPDATE_USER_PROFILE_SUCCESS',
  UPDATE_USER_PROFILE_FAILURE: 'UPDATE_USER_PROFILE_FAILURE',

  DELETE_USER: 'DELETE_USER',
  DELETE_USER_SUCCESS: 'DELETE_USER_SUCCESS',
  DELETE_USER_FAILURE: 'DELETE_USER_FAILURE',

  CREATE_ENVIRONMENT: 'CREATE_ENVIRONMENT',
  CREATE_ENVIRONMENT_SUCCESS: 'CREATE_ENVIRONMENT_SUCCESS',
  CREATE_ENVIRONMENT_FAILURE: 'CREATE_ENVIRONMENT_FAILURE',

  EDIT_ENVIRONMENT: 'EDIT_ENVIRONMENT',
  EDIT_ENVIRONMENT_SUCCESS: 'EDIT_ENVIRONMENT_SUCCESS',
  EDIT_ENVIRONMENT_FAILURE: 'EDIT_ENVIRONMENT_FAILURE',

  GET_ENVIRONMENTS_LIST: 'GET_ENVIRONMENTS_LIST',
  GET_ENVIRONMENTS_LIST_SUCCESS: 'GET_ENVIRONMENTS_LIST_SUCCESS',
  GET_ENVIRONMENTS_LIST_FAILURE: 'GET_ENVIRONMENTS_LIST_FAILURE',

  DELETE_ENVIRONMENT: 'DELETE_ENVIRONMENT',
  DELETE_ENVIRONMENT_SUCCESS: 'DELETE_ENVIRONMENT_SUCCESS',
  DELETE_ENVIRONMENT_FAILURE: 'DELETE_ENVIRONMENT_FAILURE',

  RESET_ENVIRONMENTS_PROPS: 'RESET_ENVIRONMENTS_PROPS',

  RESET_ENVIRONMENTS_ERRORS: 'RESET_ENVIRONMENTS_ERRORS',

  SEARCH_ENVIRONMENTS: 'SEARCH_ENVIRONMENTS',
  SEARCH_ENVIRONMENTS_SUCCESS: 'SEARCH_ENVIRONMENTS_SUCCESS',
  SEARCH_ENVIRONMENTS_FAILURE: 'SEARCH_ENVIRONMENTS_FAILURE',
  SEARCH_ENVIRONMENTS_RESET: 'SEARCH_ENVIRONMENTS_RESET',

  CATEGORIZE_ENVIRONMENTS: 'CATEGORIZE_ENVIRONMENTS',
  CATEGORIZE_ENVIRONMENTS_SUCCESS: 'CATEGORIZE_ENVIRONMENTS_SUCCESS',
  CATEGORIZE_ENVIRONMENTS_FAILURE: 'CATEGORIZE_ENVIRONMENTS_FAILURE',
  CATEGORIZE_ENVIRONMENTS_RESET: 'CATEGORIZE_ENVIRONMENTS_RESET',

  GET_REPOSITORIES: 'GET_REPOSITORIES',
  GET_REPOSITORIES_SUCCESS: 'GET_REPOSITORIES_SUCCESS',
  GET_REPOSITORIES_FAILURE: 'GET_REPOSITORIES_FAILURE',

  GET_TOPICS: 'GET_TOPICS',
  GET_TOPICS_SUCCESS: 'GET_TOPICS_SUCCESS',
  GET_TOPICS_FAILURE: 'GET_TOPICS_FAILURE',

  CREATE_IMAGE: 'CREATE_IMAGE',
  CREATE_IMAGE_SUCCESS: 'CREATE_IMAGE_SUCCESS',
  CREATE_IMAGE_FAILURE: 'CREATE_IMAGE_FAILURE',

  GET_USER_IMAGES_LIST: 'GET_USER_IMAGES_LIST',
  GET_USER_IMAGES_LIST_SUCCESS: 'GET_USER_IMAGES_LIST_SUCCESS',
  GET_USER_IMAGES_LIST_FAILURE: 'GET_USER_IMAGES_LIST_FAILURE',

  GET_IMAGE_CONFIG_LIST: 'GET_IMAGE_CONFIG_LIST',
  GET_IMAGE_CONFIG_LIST_SUCCESS: 'GET_IMAGE_CONFIG_LIST_SUCCESS',
  GET_IMAGE_CONFIG_LIST_FAILURE: 'GET_IMAGE_CONFIG_LIST_FAILURE',

  DELETE_IMAGE: 'DELETE_IMAGE',
  DELETE_IMAGE_SUCCESS: 'DELETE_IMAGE_SUCCESS',
  DELETE_IMAGE_FAILURE: 'DELETE_IMAGE_FAILURE',

  RESET_IMAGE_PROPS: 'RESET_IMAGE_PROPS',

  GET_CONTRIBUTORS_LIST: 'GET_CONTRIBUTORS_LIST',
  GET_CONTRIBUTORS_LIST_SUCCESS: 'GET_CONTRIBUTORS_LIST_SUCCESS',
  GET_CONTRIBUTORS_LIST_FAILURE: 'GET_CONTRIBUTORS_LIST_FAILURE',

  GET_PROJECTAUTHORS_LIST: 'GET_PROJECTAUTHORS_LIST',
  GET_PROJECTAUTHORS_LIST_SUCCESS: 'GET_PROJECTAUTHORS_LIST_SUCCESS',
  GET_PROJECTAUTHORS_LIST_FAILURE: 'GET_PROJECTAUTHORS_LIST_FAILURE',

  GET_USER_REPOSITORIES_LIST: 'GET_USER_REPOSITORIES_LIST',
  GET_USER_REPOSITORIES_LIST_SUCCESS: 'GET_USER_REPOSITORIES_LIST_SUCCESS',
  GET_USER_REPOSITORIES_LIST_FAILURE: 'GET_USER_REPOSITORIES_LIST_FAILURE',

  FIND_GYM_REPOS: 'FIND_GYM_REPOS',
  FIND_GYM_REPOS_SUCCESS: 'FIND_GYM_REPOS_SUCCESS',
  FIND_GYM_REPOS_FAILURE: 'FIND_GYM_REPOS_FAILURE',

  CREATE_MESSAGEBOARD: 'CREATE_MESSAGEBOARD',
  CREATE_MESSAGEBOARD_SUCCESS: 'CREATE_MESSAGEBOARD_SUCCESS',
  CREATE_MESSAGEBOARD_FAILURE: 'CREATE_MESSAGEBOARD_FAILURE',

  EDIT_MESSAGEBOARD: 'EDIT_MESSAGEBOARD',
  EDIT_MESSAGEBOARD_SUCCESS: 'EDIT_MESSAGEBOARD_SUCCESS',
  EDIT_MESSAGEBOARD_FAILURE: 'EDIT_MESSAGEBOARD_FAILURE',

  GET_MESSAGEBOARDS_LIST: 'GET_MESSAGEBOARDS_LIST',
  GET_MESSAGEBOARDS_LIST_SUCCESS: 'GET_MESSAGEBOARDS_LIST_SUCCESS',
  GET_MESSAGEBOARDS_LIST_FAILURE: 'GET_MESSAGEBOARDS_LIST_FAILURE',

  DELETE_MESSAGEBOARD: 'DELETE_MESSAGEBOARD',
  DELETE_MESSAGEBOARD_SUCCESS: 'DELETE_MESSAGEBOARD_SUCCESS',
  DELETE_MESSAGEBOARD_FAILURE: 'DELETE_MESSAGEBOARD_FAILURE',

  RESET_MESSAGEBOARDS_PROPS: 'RESET_MESSAGEBOARDS_PROPS',

  RESET_MESSAGEBOARDS_ERRORS: 'RESET_MESSAGEBOARDS_ERRORS',

  COUNT_COMMENTS: 'COUNT_COMMENTS',
  COUNT_COMMENTS_SUCCESS: 'COUNT_COMMENTS_SUCCESS',
  COUNT_COMMENTS_FAILURE: 'COUNT_COMMENTS_FAILURE',
};
